# Generated by Django 2.1.5 on 2019-12-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sko', '0005_listing_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
