# Generated by Django 2.1.5 on 2019-12-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sko', '0006_listing_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cond',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='course',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
