# Generated by Django 2.1.5 on 2019-12-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sko', '0003_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
