# Generated by Django 2.1.5 on 2019-12-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sko', '0004_auto_20191205_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone',
            field=models.CharField(default='123123123', max_length=12),
            preserve_default=False,
        ),
    ]
